AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Layout/LineLength:
  Max: 160

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 60

Metrics/ClassLength:
  Max: 400

Metrics/ModuleLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Naming/PredicateMethod:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
